apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataservice
  namespace: chaos-demo
  labels:
    app: dataservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataservice
  template:
    metadata:
      labels:
        app: dataservice
      annotations:
        chaos-mesh.org/inject: "true"
    spec:
      containers:
      - name: dataservice
        image: mychaos-dataservice:latest
        imagePullPolicy: IfNotPresent
        workingDir: /app
        command: ["python", "app.py"]
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: dataservice
  namespace: chaos-demo
spec:
  selector:
    app: dataservice
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
